export {
  default,
  addPage,
  setActivePage,
  addItemToPage,
  setAllItemsInPage,
  updateItemInPage,
  deleteItemFromPage,
  clearPage,
  clearAllPages,
  renamePage,
  loadPages,
  setProjectName,
  removePage,
  setGroups,
  addGroup,
  updateGroup,
  deleteGroup,
  updateItemsInPage,
  deleteItemsFromPage,
  createComponentGroup,
  ungroupComponent,
  renameComponentGroup,
} from '../../shared/store/pageSlice';

export type { ComponentGroup } from '../../shared/store/pageSlice';
